version: '3.8'

services:
  app_primer:
    build: ./PrimerApi
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://primerapidb:3306/primerapidb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 2083
    restart: always
    depends_on:
      - primerapidb

  primerapidb:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2083
      MYSQL_PASSWORD: 2083
      MYSQL_DATABASE: primerapidb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
